DentalDB/Models/USUARIO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class USUARIO
    {
        [Key]
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }

        [DataType(DataType.Password)]
        public string Contrasena { get; set; }
    }
}

DentalDB/Controllers/USUARIOController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DentalDB.Models;

namespace DentalDB.Controllers
{
    public class USUARIOController : Controller
    {
        DentalDBEntities1 db = new DentalDBEntities1();

        // GET: USUARIO
        public ActionResult Index(USUARIO usuario)
        {
            if (ModelState.IsValid)
            {
                var query = db.USUARIO.Where(x => x.Nombre.Equals(usuario.Nombre) && x.Contrasena.Equals(usuario.Contrasena)).FirstOrDefault();
                if (query != null)
                {
                    Session["Id"] = usuario.IdUsuario.ToString();
                    Session["Nombre"] = usuario.Nombre.ToString();

                    return RedirectToAction("Index", "CITA");
                }
                else
                {
                    ViewBag.Message = "Error";
                }
                
            }
            return View(usuario);
        }

        // GET: USUARIO/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: USUARIO/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: USUARIO/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: USUARIO/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: USUARIO/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: USUARIO/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: USUARIO/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]

        public ActionResult listado()
        {
            var query = from p in db.PACIENTE
                        join t in db.TRABAJO on p.IdPaciente equals t.IdTrabajo
                        //join l in db.LABORATORIO on p.IdPaciente equals l.IdLaboratorio
                        select new { p.Nombre, t.Tratamiento };
            return View();
        }

        [HttpGet]
        public ActionResult inicio()
        {
            return View();
        }
    }
}

DentalDB/Views/USUARIO/Index.cshtml
@model DentalDB.Models.USUARIO

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Login.cshtml";
}



@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contrasena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contrasena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contrasena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ENTRAR" class="btn btn-default" />
            </div>
        </div>
    </div>
}

DentalDB/Views/USUARIO/inicio.cshtml
@model DentalDB.Models.USUARIO

@{
    Layout = null;
}

@*<!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Inicio</title>
        <link href="~/Content/bootstrap.css" rel="stylesheet" />


        <style>

            #foto {
               width:300px;
               height:300px;
               margin-bottom:15px;
               margin-left:10px;

            }


            #menu{

               height:50px;
               margin-bottom:15px;
               margin-left:10px;
            }



            #cuerpo{
                margin-left:10px;
            }
        </style>
    </head>
    <body>
        <div>
            <div id="Contenedor">
                <div id="foto">
                    <img src="~/bloggif_5a5eb769bbbcb.jpeg" />
                </div>
                <div id="menu" class="nav navbar-inverse" style="text-align:right;">
                    <font size="5" style="margin-right:5px;">
                        @Html.ActionLink("Iniciar", "Index", "USUARIO")
                    </font>
                </div>

                <div id="cuerpo">
                    <img src="~/iconos-contactos-google-1-6-700x300.jpg" />
                    <br />
                    <div id="eso">
                        <div style="text-align:center;" class="col-lg-2">
                            <p>
                                <strong>ACERCA DE</strong><br />
                                Miguel Angel Carela estudió en la Universidad Central del Este(UCE),
                                donde se graduó de Doctor en Odontologia en el año 2009
                            </p>
                        </div>

                        <div style="text-align:center" class="col-lg-2">
                            <p>
                                <strong>SERVICIOS</strong><br />
                                Prótesis sobre Implante
                            </p>
                        </div>

                        <div style="text-align:center" class="col-lg-3">
                            <p>
                                <strong>CONTACTOS</strong><br />
                                Telefono: 829-865-0432 <br />
                                Correo: doctorcarelagutierrez@gmail.com
                            </p>
                        </div>

                        <div style="text-align:center" class="col-lg-4">
                            <p>
                                <strong>LUGARES DONDE LABORA</strong><br />
                                IODE- Instituito Odontologico del Este <br />
                                DISPENSARIO MEDICO MADRE CARMEN <br />
                                POLICIA NACIONAL- UNAPEC <br />
                                CONSULTORIO DENTAL DRA. MAGARITE BRASSAN <br />
                            </p>
                        </div>
                    </div>
                </div>

                <div id="pie">

                </div>
            </div>
        </div>
    </body>
    </html>*@



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <title>DR CARELA</title>
    <!-- Bootstrap core CSS -->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Static navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a class="navbar-brand" href="index.html">INSTANT</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active"><a href="index.html">
                         @Html.ActionLink("Inicio","Index","USUARIO")
                         </a></li>
                    
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div id="headerwrap">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-lg-offset-3">
                    <h4>GRACIAS POR PREFERIRME, SOY EL DR. CARELA</h4>
                    <h1>MIGUEL ANGEL CARELA</h1>
                    <h4>DOCTOR EN ODONTOLOGIA, IMPLANTOLOGO</h4>
                </div>
            </div><! --/row -->
        </div> <!-- /container -->
    </div><! --/headerwrap -->

    <section id="works"></section>
    <div class="container">
        <div class="row centered mt mb">
            <h1>Acerca de mi</h1>
            <div id="eso">
                <div style="text-align:center;" class="col-lg-2">
                    <p>
                        <strong>ACERCA DE</strong><br />
                        Miguel Angel Carela estudió en la Universidad Central del Este(UCE),
                        donde se graduó de Doctor en Odontologia en el año 2009
                    </p>
                </div>

                <div style="text-align:center" class="col-lg-2">
                    <p>
                        <strong>SERVICIOS</strong><br />
                        Prótesis sobre Implante
                    </p>
                </div>

                <div style="text-align:center" class="col-lg-3">
                    <p>
                        <strong>CONTACTOS</strong><br />
                        Telefono: 829-865-0432 <br />
                        Correo: doctorcarelagutierrez@gmail.com
                    </p>
                </div>

                <div style="text-align:center" class="col-lg-4">
                    <p>
                        <strong>LUGARES DONDE LABORA</strong><br />
                        IODE- Instituito Odontologico del Este <br />
                        DISPENSARIO MEDICO MADRE CARMEN <br />
                        POLICIA NACIONAL- UNAPEC <br />
                        CONSULTORIO DENTAL DRA. MAGARITE BRASSAN <br />
                    </p>
                </div>
            </div>

        </div><! --/row -->
    </div><! --/container -->

    <div id="social">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-2">
                    <a href="#"><i class="fa fa-dribbble"></i></a>
                </div>
                <div class="col-lg-2">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                </div>
                <div class="col-lg-2">
                    <a href="#"><i class="fa fa-twitter"></i></a>
                </div>
                <div class="col-lg-2">
                    <a href="#"><i class="fa fa-linkedin"></i></a>
                </div>
                <div class="col-lg-2">
                    <a href="#"><i class="fa fa-instagram"></i></a>
                </div>
                <div class="col-lg-2">
                    <a href="#"><i class="fa fa-tumblr"></i></a>
                </div>

            </div><! --/row -->
        </div><! --/container -->
    </div><! --/social -->

    <div id="footerwrap">
        <div class="container">
            <div class="row centered">
                <div class="col-lg-4">
                    @*<p><b>WEB DESIGNER, DEVELOPER & GAME ADDICT</b></p>*@
                </div>

                <div class="col-lg-4">
                    @*<p>Living in the amazing London.</p>*@
                </div>
                <div class="col-lg-4">
                    @*<p>hello@instant.com</p>*@
                </div>
            </div>
        </div>
    </div><! --/footerwrap -->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
</body>
</html>